help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_define_assertions_and_warnings

.PHONY: build-02_define_assertions_and_warnings
build-02_define_assertions_and_warnings: 
	cd 02_define_assertions_and_warnings && make build
