help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-01_map_process_instances build-02_define_a_computed_property build-03_define_a_resource build-04_define_interaction build-05_model_a_collection_resource build-07_define_a_virtual_resource_interaction build-08_execute_another_process

.PHONY: build-01_map_process_instances
build-01_map_process_instances: 
	cd 01_map_process_instances && make build

.PHONY: build-02_define_a_computed_property
build-02_define_a_computed_property: 
	cd 02_define_a_computed_property && make build

.PHONY: build-03_define_a_resource
build-03_define_a_resource: 
	cd 03_define_a_resource && make build

.PHONY: build-04_define_interaction
build-04_define_interaction: 
	cd 04_define_interaction && make build\

.PHONY: build-05_visualise_simulated_outcomes
build-05_visualise_simulated_outcomes: 
	cd 05_visualise_simulated_outcomes && make build

.PHONY: build-05_model_a_collection_resource
build-05_model_a_collection_resource: 
	cd 05_model_a_collection_resource && make build

.PHONY: build-07_define_a_virtual_resource_interaction
build-07_define_a_virtual_resource_interaction: 
	cd 07_define_a_virtual_resource_interaction && make build

.PHONY: build-08_execute_another_process
build-08_execute_another_process: 
	cd 08_execute_another_process && make build
	