help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-01_what_is_a_template build-02_merge_templates

.PHONY: build-01_what_is_a_template
build-01_what_is_a_template: 
	cd 01_what_is_a_template && make build

.PHONY: build-02_merge_templates
build-02_merge_templates: 
	cd 02_merge_templates && make build
