help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-00 build-01 build-02 build-03 build-04 build-05
 
.PHONY: build-00
build-00:
	cd 00 && npm install

.PHONY: build-01
build-01:
	cd 01 && npm install

.PHONY: build-02
build-02:
	cd 02 && npm install
	
.PHONY: build-03
build-03:
	cd 03 && npm install
	
.PHONY: build-04
build-04:
	cd 04 && npm install
	
.PHONY: build-05
build-05:
	cd 05 && npm install