help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_work_with_a_blobtype_datastream build-03_validate_a_blobtype

.PHONY: build-02_work_with_a_blobtype_datastream
build-02_work_with_a_blobtype_datastream: 
	cd 02_work_with_a_blobtype_datastream && make build

.PHONY: build-03_validate_a_blobtype
build-03_validate_a_blobtype: 
	cd 03_validate_a_blobtype && make build
