help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-00 build-01

.PHONY: build-00
build-00:
	cd 00 && npm install && edk template build

.PHONY: build-01
build-00:
	cd 01 && npm install && edk template build