help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-03_define_a_pipeline_operation build-05_define_an_expression build-06_handle_missing_values

.PHONY: build-03_define_a_pipeline_operation
build-03_define_a_pipeline_operation: 
	cd 03_define_a_pipeline_operation && make build

.PHONY: build-05_define_an_expression
build-05_define_an_expression: 
	cd 05_define_an_expression && make build

.PHONY: build-06_handle_missing_values
build-06_handle_missing_values: 
	cd 06_handle_missing_values && make build
