help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-visualize_in_accordions build-visualize_in_pages build-visualize_in_panels build-visualize_in_tabs build-visualize_with_charts build-visualize_with_forms visualize_with_pivots build-visualize_with_planners build-visualize_with_tables

.PHONY: build-visualize_in_accordions
build-visualize_in_accordions:
	cd visualize_in_accordions && make build

.PHONY: build-visualize_in_pages
build-visualize_in_pages:
	cd visualize_in_pages && make build

.PHONY: build-visualize_in_panels
build-visualize_in_panels:
	cd visualize_in_panels && make build

.PHONY: build-visualize_in_tabs
build-visualize_in_tabs:
	cd visualize_in_tabs && make build

.PHONY: build-visualize_with_charts
build-visualize_with_charts:
	cd visualize_with_charts && make build

.PHONY: build-visualize_with_forms
build-visualize_with_forms:
	cd visualize_with_forms && make build

.PHONY: build-visualize_with_pivots
build-visualize_with_pivots:
	cd visualize_with_pivots && make build

.PHONY: build-visualize_with_planners
build-visualize_with_planners: 
	cd visualize_with_planners && make build

.PHONY: build-visualize_with_tables
build-visualize_with_tables: 
	cd visualize_with_tables && make build