help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-ingest-data

.PHONY: build-ingest-data
build-ingest-data: 
	cd ingest-data && make build