help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-04_define_a_process build-06_define_a_scenario

.PHONY: build-04_define_a_process
build-04_define_a_process: 
	cd 04_define_a_process && make build

.PHONY: build-06_define_a_scenario
build-06_define_a_scenario: 
	cd 06_define_a_scenario && make build