help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-01_present_actionable_insights build-02_present_interactive_insights

.PHONY: build-01_present_actionable_insights
build-01_present_actionable_insights: 
	cd 01_present_actionable_insights && make build

.PHONY: build-02_present_interactive_insights
build-02_present_interactive_insights: 
	cd 02_present_interactive_insights && make build
