help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_present_actionable_insights build-03_present_interactive_insights

.PHONY: build-02_present_actionable_insights
build-02_present_actionable_insights: 
	cd 02_present_actionable_insights && make build

.PHONY: build-03_present_interactive_insights
build-03_present_interactive_insights: 
	cd 03_present_interactive_insights && make build
