help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_present_actionable_insights build-03_define_reporting build-04_present_interactive_insights

.PHONY: build-02_present_actionable_insights
build-02_present_actionable_insights: 
	cd 02_present_actionable_insights && make build

.PHONY: build-03_define_reporting
build-03_define_reporting: 
	cd 03_define_reporting && make build

.PHONY: build-04_present_interactive_insights
build-04_present_interactive_insights: 
	cd 04_present_interactive_insights && make build
