help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_use_a_dicttype_datastream build-03_use_a_structtype_in_a_dicttype_datastream

.PHONY: build-02_use_a_dicttype_datastream
build-02_use_a_dicttype_datastream: 
	cd 02_use_a_dicttype_datastream && make build

.PHONY: build-03_use_a_structtype_in_a_dicttype_datastream
build-03_use_a_structtype_in_a_dicttype_datastream: 
	cd 03_use_a_structtype_in_a_dicttype_datastream && make build
