help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-01_define_table_visual build-02_define_graph_visual build-03_define_tabbed_visual build-04_define_panelled_visual build-05_define_interactive_visual build-06_define_header_visual

.PHONY: build-01_define_table_visual
build-01_define_table_visual: 
	cd 01_define_table_visual && make build

.PHONY: build-02_define_graph_visual
build-02_define_graph_visual: 
	cd 02_define_graph_visual && make build

.PHONY: build-03_define_tabbed_visual
build-03_define_tabbed_visual: 
	cd 03_define_tabbed_visual && make build

.PHONY: build-04_define_panelled_visual
build-04_define_panelled_visual: 
	cd 04_define_panelled_visual && make build

.PHONY: build-05_define_interactive_visual
build-05_define_interactive_visual: 
	cd 05_define_interactive_visual && make build

.PHONY: build-06_define_header_visual
build-06_define_header_visual: 
	cd 06_define_header_visual && make build
