help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_send_data

.PHONY: build-02_send_data
build-02_send_data: 
	cd 02_send_data && make build
