help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_define_and_launch_a_csv_datasource build-03_define_and_launch_a_json_datasource

.PHONY: build-02_define_and_launch_a_csv_datasource
build-02_define_and_launch_a_csv_datasource: 
	cd 02_define_and_launch_a_csv_datasource && make build

.PHONY: build-03_define_and_launch_a_json_datasource
build-03_define_and_launch_a_json_datasource: 
	cd 03_define_and_launch_a_json_datasource && make build
