help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-01_define_a_prescriptive_scenario build-03_define_an_objective build-05_define_an_optimized_resource build-06_generate_prescriptive_insights build-07_optimize_a_categorical_choice

.PHONY: build-01_define_a_prescriptive_scenario
build-01_define_a_prescriptive_scenario: 
	cd 01_define_a_prescriptive_scenario && make build

.PHONY: build-03_define_an_objective
build-03_define_an_objective: 
	cd 03_define_an_objective && make build

.PHONY: build-05_define_an_optimized_resource
build-05_define_an_optimized_resource: 
	cd 05_define_an_optimized_resource && make build

.PHONY: build-06_generate_prescriptive_insights
build-06_generate_prescriptive_insights: 
	cd 06_generate_prescriptive_insights && make build
	
.PHONY: build-07_optimize_a_categorical_choice
build-07_optimize_a_categorical_choice: 
	cd 07_optimize_a_categorical_choice && make build
	