help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_define_a_file_datasource

.PHONY: build-02_define_a_file_datasource
build-02_define_a_file_datasource: 
	cd 02_define_a_file_datasource && make build
