help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-02_define_a_varianttype build-03_transform_varianttype_data build-04_handle_optional_data

.PHONY: build-02_define_a_varianttype
build-02_define_a_varianttype: 
	cd 02_define_a_varianttype && make build

.PHONY: build-03_transform_varianttype_data
build-03_transform_varianttype_data: 
	cd 03_transform_varianttype_data && make build

.PHONY: build-04_handle_optional_data
build-04_handle_optional_data: 
	cd 04_handle_optional_data && make build
