help:
	@echo "Usage examples:"
	@echo ""
	@echo "    make build"
	@echo "    make help"

.PHONY: build
build: build-03_filter_a_collection build-04_disaggregate_a_collection_field build-05_join_collections build-06_concatenate_collections build-07_aggregate_a_collection build-08_offset_a_collection_datastream build-09_select_a_collection build-10_encode_to_json

.PHONY: build-03_filter_a_collection
build-03_filter_a_collection: 
	cd 03_filter_a_collection && make build

.PHONY: build-04_disaggregate_a_collection_field
build-04_disaggregate_a_collection_field: 
	cd 04_disaggregate_a_collection_field && make build

.PHONY: build-05_join_collections
build-05_join_collections: 
	cd 05_join_collections && make build

.PHONY: build-06_concatenate_collections
build-06_concatenate_collections: 
	cd 06_concatenate_collections && make build

.PHONY: build-07_aggregate_a_collection
build-07_aggregate_a_collection: 
	cd 07_aggregate_a_collection && make build

.PHONY: build-08_offset_a_collection_datastream
build-08_offset_a_collection_datastream: 
	cd 08_offset_a_collection_datastream && make build
	
.PHONY: build-09_select_a_collection
build-09_select_a_collection: 
	cd 09_select_a_collection && make build

.PHONY: build-10_encode_to_json
build-10_encode_to_json: 
	cd 10_encode_to_json && make build
